from typing import List, Optional, Dict, Any, Union
import numpy as np

class BusHandle: ...
class LineHandle: ...
class TrafoHandle: ...
class LoadHandle: ...
class GenHandle: ...
class ExtGridHandle: ...
class ShuntHandle: ...
class SGenHandle: ...
class SwitchHandle: ...

class PowerGrid:
    def __init__(self, case_path: Optional[str] = None, qlim: bool = False, **kwargs: Any) -> None: ...
    def set_base(self, f_hz: float = 50.0, sn_mva: float = 100.0) -> None: ...
    def add_bus(self, id: int, vn_kv: float, name: Optional[str] = None, 
                vm_min: float = 0.9, vm_max: float = 1.1, zone: int = 0) -> BusHandle: ...
    def add_line(self, from_bus: int, to_bus: int, length_km: float, 
                 std_type: Optional[str] = None, **kwargs: Any) -> LineHandle: ...
    def add_load(self, bus: int, p_mw: float, q_mvar: float, name: Optional[str] = None) -> LoadHandle: ...
    def add_gen(self, bus: int, p_mw: float, vm_pu: float = 1.0, **kwargs: Any) -> GenHandle: ...
    def add_ext_grid(self, bus: int, vm_pu: float = 1.0, va_degree: float = 0.0, 
                     name: Optional[str] = None) -> ExtGridHandle: ...
    def init_pf(self) -> None: ...
    def solve(self) -> None: ...
    def run_pf(self) -> None: ...
    def post_process(self) -> None: ...
    def get_bus_results(self) -> Dict[str, np.ndarray]: ...
    def get_line_results(self) -> Dict[str, np.ndarray]: ...
    
    @property
    def iterations(self) -> int: ...
    @property
    def converged(self) -> bool: ...
    @property
    def time(self) -> float: ...
    @property
    def v(self) -> np.ndarray: ...
    @property
    def y_bus(self) -> Dict[str, np.ndarray]: ...

class solver:
    class NewtonSolver:
        def __init__(self) -> None: ...
        def setup_context(self, 
                          y_indptr: np.ndarray, 
                          y_indices: np.ndarray, 
                          y_data: np.ndarray, 
                          s_bus: np.ndarray, 
                          v_init: np.ndarray, 
                          p_vec: List[int], 
                          p_inv: List[int], 
                          npv: int, 
                          npq: int) -> None: ...
        def solve(self) -> bool: ...
        def get_voltage(self) -> np.ndarray: ...

def version() -> str: ...
def features() -> List[str]: ...
